name: zawiid
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.0.2
  badges: ^3.1.2
  floating_bottom_navigation_bar: ^1.5.2
  readmore: ^3.0.0
  flutter_screenutil: ^5.9.1
  linear_progress_bar: ^1.1.1
  expandable_page_view: ^1.0.17
  pinput: ^3.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  firebase_core: ^2.27.0
  flutter_native_splash: ^2.3.10
  firebase_messaging: ^14.7.19
  googleapis_auth: ^1.6.0
  device_info_plus: ^9.1.2
  intl_phone_field: ^3.2.0
  flutter_local_notifications: ^17.2.1+2
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0



flutter_native_splash:
  color: "#000000" # Correct color format
  image: assets/log/Splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: fill
  android_12:
    color: "#000000"
    image: assets/log/Splash.png
    android_gravity: fill


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/log/LOGO-icon---green.png
    - assets/svg/002-password.svg
    - assets/svg/001-mail.svg
    - assets/log/LOGO-icon---Black.png
    - assets/img/pop.png
    - assets/img/User.png
    - assets/img/PrivacyAndTermsImage/PrivacyAndPolicy.png
    - assets/img/PrivacyAndTermsImage/TermsofService.png
    - assets/img/CustomerService/Group.png
    - assets/img/CustomerService/mail.png
    - assets/img/CustomerService/speech.png
    - assets/img/CustomerService/CustomerServices.png
    - assets/svg-profile/Group.svg
    - assets/svg-profile/icon.svg
    - assets/svg-profile/icons.svg
    - assets/svg-profile/language.svg
    - assets/svg-profile/Path.svg
    - assets/svg-profile/shipping.svg
    - assets/svg-profile/whatsapp.svg
    - assets/svg/cart.png
    - assets/svg/notification.png
    - assets/img/camera.png
    - assets/svg/buy.svg
    - assets/img/sddefault.png
    - assets/svg/search.svg
    - assets/img/watch.png
    - assets/svg/arrow.svg
    - assets/svg/arrow_down.svg
    - assets/svg/arrow_up.svg
    - assets/img/pop2.png
    - assets/log/Splash.png
    - assets/img/applepayment.png
    - assets/img/knet.png
    - assets/img/master.png
    - assets/img/pop3.png
    - assets/svg/close.svg
    - assets/svg/delivery.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: MyFlutterApp
       fonts:
         - asset: icons/MyFlutterApp.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
